- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{component}}"

- name: Installing Nginx.
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Removing default Nginx content.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating default Nginx content.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading the frontend web layer code.
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Configuring reverse proxy settings.
  ansible.builtin.copy:
    src: 1-reverse-proxy.conf
    dest: /etc/nginx/default.d/reverse-proxy.conf

- name: Restarting and enabling the Nginx service.
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true

- name: Creating Nginx Node Exporter Directory.
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: Downloading the Nginx Node Exporter.
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: Configuring Nginx Node Exporter Service File.
  ansible.builtin.copy:
    src: nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Restarting and enabling the Nginx Node Exporter.
  ansible.builtin.systemd_service:
    name: nginx_exporter
    state: restarted
    enabled: true
    daemon_reload: true

- name: Setup Filebeat.
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat.yml