- name: Configure ELK Repository
  ansible.builtin.template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Import the Elastic GPG key
  ansible.builtin.shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install Elasticsearch.
  ansible.builtin.shell: yum install -y elasticsearch &>> /tmp/output

- name: Enabling and restarting the service.
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: restarted
    enabled: true
    daemon_reload: true

- name: Install Kibana and Nginx
  ansible.builtin.yum:
    name:
      - nginx
      - kibana
      - bash-completion
    state: present

- name: Configure Reverse Proxy for Kibana
  ansible.builtin.template:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"

- name: Enabling and restarting the service.
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - kibana
    - nginx