- name: Configure ELK Repository
  ansible.builtin.copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Import the Elastic GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install Elasticsearch and Kibana
  ansible.builtin.yum:
    name:
      - elasticsearch
      - kibana
    state: present
  register: install_output
  ignore_errors: yes  # Capture output even if there's an error

- name: Write installation output to file
  ansible.builtin.copy:
    content: "{{ install_output.msg | default(install_output.results | join('\n')) }}"
    dest: "/tmp/output"
