- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{component}}"

- name: Install Python3.12 pip
  ansible.builtin.yum:
    name: python3.12-pip
    state: present

- name: Install botocore and boto3 using pip3.12
  ansible.builtin.shell: python3.12 -m pip install botocore boto3

- name: Configure Elasticsearch
  ansible.builtin.import_tasks: elk.yml
  when: elk_component == "elk"

- name: Configure Logstash
  ansible.builtin.import_tasks: logstash.yml
  when: elk_component == "logstash"