- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{component}}"

- name: Import task from nodejs.yml.
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Setup Filebeat.
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat.yml