- name: Creating the application user.
  ansible.builtin.user:
    name: roboshop
    comment: Application User

- name: Removing the old {{component}} application directory.
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating the old {{component}} application directory.
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Downloading the {{component}} web layer code.
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Downloading the {{component}} web layer code from Nexus.
  ansible.builtin.unarchive:
    src: http://{{username}}:{{password}}@172.31.66.144:8081/repository/{{component}}/{{component}}-{{appVersion}}.zip
    dest: /app
    remote_src: yes
  vars:
    username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.username', region='us-east-1 }}"
    password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{env}}.password', region='us-east-1 }}"
    appVersion: "{{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.appVersion', region='us-east-1 }}"


