- name: Installing Python 3.6, GCC (Compiler), and Python Development Build Tools.
  ansible.builtin.dnf:
    name:
      - python36
      - gcc
      - python3-devel

- name: Import task from app-prerequisites.yml
  ansible.builtin.import_tasks: app-prerequisites.yml

- name: Installing the required Python dependencies.
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Import task from systemd_setup.yml
  ansible.builtin.import_tasks: systemd_setup.yml

- name: Setup Filebeat.
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat.yml